### ISSUE TITLE
RuntimeError: cannot cache function '__shear_dense'

### ISSUE THREAD

**Issue by AlexCzar** [synesthesiam/coqui-docker#4]
Both `tts-server` and `tts-server --update` result in:
```
Traceback (most recent call last):
  File "/app/bin/tts-server", line 5, in <module>
    from TTS.server.server import main
  File "/app/lib/python3.7/site-packages/TTS/server/server.py", line 14, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/app/lib/python3.7/site-packages/TTS/utils/synthesizer.py", line 10, in <module>
    from TTS.tts.utils.speakers import SpeakerManager
  File "/app/lib/python3.7/site-packages/TTS/tts/utils/speakers.py", line 12, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/app/lib/python3.7/site-packages/TTS/utils/audio.py", line 3, in <module>
    import librosa
  File "/app/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/app/lib/python3.7/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/app/lib/python3.7/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/app/lib/python3.7/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/app/lib/python3.7/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/app/lib/python3.7/site-packages/librosa/util/utils.py", line 1848, in <module>
    def __shear_dense(X, factor=+1, axis=-1):
  File "/app/lib/python3.7/site-packages/numba/core/decorators.py", line 214, in wrapper
    disp.enable_caching()
  File "/app/lib/python3.7/site-packages/numba/core/dispatcher.py", line 812, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/app/lib/python3.7/site-packages/numba/core/caching.py", line 610, in __init__
    self._impl = self._impl_class(py_func)
  File "/app/lib/python3.7/site-packages/numba/core/caching.py", line 348, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/app/lib/python3.7/site-packages/librosa/util/utils.py'
```

**Comment by xorbital** [comment]
Add `-e "NUMBA_CACHE_DIR=/tmp/"` to your `docker run` command
